Repository codestates-seb/seb42_main_032, pull requests merged in 2023-03, with the labels that each got.

#20 Feat be/member entity 1차
  tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Detail.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Member.java
Labels: feat, implement

#26 Feat be/category
  tikkle-be/build.gradle
  tikkle-be/src/main/java/DabuOps/tikkle/category/controller/CategoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/dto/CategoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/entity/Category.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/mapper/CategoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/repogitory/CategoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/repository/categoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/category/service/CategoryService.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/exception/ExceptionCode.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/controller/MemberCategoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/dto/MemberCategoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/entity/MemberCategory.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/mapper/MemberCategoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/repogitory/MemberCategoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryService.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceStub.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryService.java
Labels: feat, implement

#28 Feat be/member testing 및 asciidocs 구현 기초
  tikkle-be/build.gradle
  tikkle-be/src/docs/asciidoc/index.adoc
  tikkle-be/src/main/generated/DabuOps/tikkle/member/mapper/MemberMapperImpl.java
  tikkle-be/src/main/generated/DabuOps/tikkle/member_category/mapper/MemberCategoryMapperImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceStub.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/test/java/DabuOps/tikkle/member/controller/MemberControllerTest.java
Labels: documentation, feat

#37 Feat be/member memberserivce 구현
  tikkle-be/src/docs/asciidoc/index.adoc
  tikkle-be/src/main/java/DabuOps/tikkle/global/dto/LogInMemberDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/exception/ExceptionCode.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/repository/MemberRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberService.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceStub.java
  tikkle-be/src/test/java/DabuOps/tikkle/TikkleApplicationTests.java
  tikkle-be/src/test/java/DabuOps/tikkle/global/WithMemberDetailsSecurityContextFactory.java
  tikkle-be/src/test/java/DabuOps/tikkle/global/WithMockCustomMember.java
  tikkle-be/src/test/java/DabuOps/tikkle/member/controller/MemberControllerTest.java
Labels: feat, implement

#38 [add] ErrorResponse.java, MultiResponseDto.java, PageInfo.java
  tikkle-be/src/docs/asciidoc/index.adoc
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/ErrorResponse.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/MultiResponseDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/PageInfo.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/ResponseListDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Detail.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/controller/MemberCategoryController.java
  tikkle-be/src/main/resources/static/docs/index.html
  tikkle-be/src/test/java/DabuOps/tikkle/member/controller/MemberControllerTest.java
Labels: feat, implement

#42 Feat be/category
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/mapper/MemberCategoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/mapper/TransactionHistoryMapper.java
Labels: bug, fix

#49 [FIX] make it run
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
Labels: bug, fix

#52 Feat be/transaction history
  tikkle-be/src/main/java/DabuOps/tikkle/category/entity/Category.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/exception/ExceptionCode.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/repository/MemberCategoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/mapper/TransactionHistoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
  tikkle-be/src/main/resources/static/docs/index.html
  tikkle-be/src/test/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryControllerTest.java
Labels: feat, implement

#64 Feat be/transaction history
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/MonthlyTransactionHistoriesDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/controller/MemberCategoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceStub.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/repository/TransactionHistoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryService.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
  tikkle-be/src/main/resources/static/docs/index.html
  tikkle-be/src/test/java/DabuOps/tikkle/member_category/controller/MemberCategoryControllerTest.java
Labels: feat, fix, implement

#63 [Fix] OAuth Login structure change
  tikkle-be/build.gradle
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/UriCreator.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Member.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthAttribute.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthController.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthMemberService.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/SessionMember.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/config/CorsConfig.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/config/SecurityConfiguration.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/controller/OAuthController.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/dto/AccessTokenDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/dto/LoginDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/principal/OAuthUserInfo.java
  tikkle-be/src/main/java/DabuOps/tikkle/oauth/service/OAuthService.java
  tikkle-be/src/main/resources/templates/index.html
  tikkle-be/src/main/resources/templates/login.html
Labels: fix

#106 Feat be/member
  tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
Labels: feat, fix

#103 Feat be/business logic temp
  tikkle-be/src/main/java/DabuOps/tikkle/TikkleApplication.java
  tikkle-be/src/main/java/DabuOps/tikkle/account/entity/Account.java
  tikkle-be/src/main/java/DabuOps/tikkle/budget/dto/BudgetDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/utils/MonthlyTransactionHistoriesDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Member.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/repository/MemberRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberService.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/mapper/TransactionHistoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/userauth/controller/UserAuthController.java
  tikkle-be/src/main/java/DabuOps/tikkle/userauth/dto/ModifiedTransactionHistoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/userauth/mapper/AccountTransactionMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/userauth/service/UserAuthService.java
Labels: feat, fix, implement

#122 Feat be/business logic temp
  tikkle-be/src/main/java/DabuOps/tikkle/category/entity/Category.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/exception/ExceptionCode.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/entity/MemberCategory.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/repository/MemberCategoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/mapper/TransactionHistoryMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryService.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/userauth/controller/UserAuthController.java
Labels: feat, fix, implement

#127 [REFACTOR] 연관 객체 자동 생성 로직에서 budget 제외 및 budget 생성 메서드 추가
  tikkle-be/src/main/java/DabuOps/tikkle/budget/controller/BudgetController.java
  tikkle-be/src/main/java/DabuOps/tikkle/budget/dto/BudgetDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/budget/mapper/BudgetMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/budget/service/BudgetService.java
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
Labels: feat, fix

#147 [FIX] initMember 메서드에서 gender 수정 추가
  tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
Labels: feat, fix

#159 ExceptionAdvice 추가, Budget 매핑 오류 수정
  tikkle-be/src/main/java/DabuOps/tikkle/budget/mapper/BudgetMapper.java
  tikkle-be/src/main/java/DabuOps/tikkle/global/exception/GlobalExceptionAdvice.java
Labels: bug, feat, fix, implement

#164 [FIX] Post Budget, Post TransactionHistory 안되던 오류 수정
  tikkle-be/src/main/java/DabuOps/tikkle/budget/dto/BudgetDto.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
Labels: bug, fix

#190 [FIX] 거래내역 등록 시 해당 카테고리 예산의 spend필드에 값 누적되도록 수정
  tikkle-be/src/main/java/DabuOps/tikkle/budget/repository/BudgetRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/budget/service/BudgetServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/repository/TransactionHistoryRepository.java
  tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
Labels: feat, fix, implement
